import Head from "next/head";
import Image from "next/image";

import Main from "../components/Main";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Anushka Kulkarni | Software Developer</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main />
      <Contact />
    </div>
  );
}
